#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Thu Jul  2 20:32:09 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class BOXFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: BOXFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1332, 734))
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_canvas = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_ctrl = wx.Panel(self.panel_1, wx.ID_ANY)
        self.bitmap_button_record = wx.BitmapButton(self.panel_ctrl, wx.ID_ANY, wx.Bitmap("/home/gabriel/Proyectos/biosignals/images/record.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_play = wx.BitmapButton(self.panel_ctrl, wx.ID_ANY, wx.Bitmap("/home/gabriel/Proyectos/biosignals/images/play.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_pause = wx.BitmapButton(self.panel_ctrl, wx.ID_ANY, wx.Bitmap("/home/gabriel/Proyectos/biosignals/images/pause.png", wx.BITMAP_TYPE_ANY))
        self.bitmap_button_stop = wx.BitmapButton(self.panel_ctrl, wx.ID_ANY, wx.Bitmap("/home/gabriel/Proyectos/biosignals/images/stop.png", wx.BITMAP_TYPE_ANY))
        self.panel_time = wx.Panel(self.panel_1, wx.ID_ANY, style=wx.BORDER_SIMPLE)
        self.button_time = wx.ToggleButton(self.panel_time, wx.ID_ANY, "TIME")
        self.slider_time = wx.Slider(self.panel_time, wx.ID_ANY, 0, 0, 100)
        self.spin_ctrl_double_time = wx.SpinCtrlDouble(self.panel_time, wx.ID_ANY, "0", min=0.0, max=100.0)
        self.panel_ch_1 = wx.Panel(self.panel_1, wx.ID_ANY, style=wx.BORDER_SIMPLE)
        self.spin_ctrl_double_ch1_vd = wx.SpinCtrlDouble(self.panel_ch_1, wx.ID_ANY, "0", min=0.0, max=100.0)
        self.slider_ch1_vd = wx.Slider(self.panel_ch_1, wx.ID_ANY, 0, -10, 0, style=wx.SL_VERTICAL)
        self.button_ch1 = wx.ToggleButton(self.panel_ch_1, wx.ID_ANY, "CH 1")
        self.slider_ch1_vert = wx.Slider(self.panel_ch_1, wx.ID_ANY, 0, 0, 10, style=wx.SL_VERTICAL)
        self.button_ch1_v_rst = wx.Button(self.panel_ch_1, wx.ID_ANY, "V RST")
        self.button_ch1_h_rst = wx.Button(self.panel_ch_1, wx.ID_ANY, "H RST")
        self.slider_ch1_horz = wx.Slider(self.panel_ch_1, wx.ID_ANY, 0, 0, 10)
        self.panel_ch_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.spin_ctrl_double_ch2_vd = wx.SpinCtrlDouble(self.panel_ch_2, wx.ID_ANY, "0.0", min=0.0, max=100.0)
        self.slider_ch2_vd = wx.Slider(self.panel_ch_2, wx.ID_ANY, 0, -10, 0, style=wx.SL_VERTICAL)
        self.button_ch2 = wx.ToggleButton(self.panel_ch_2, wx.ID_ANY, "CH 1")
        self.slider_ch2_vert = wx.Slider(self.panel_ch_2, wx.ID_ANY, 0, 0, 10, style=wx.SL_VERTICAL)
        self.button_ch2_v_rst = wx.Button(self.panel_ch_2, wx.ID_ANY, "V RST")
        self.button_ch2_h_rst = wx.Button(self.panel_ch_2, wx.ID_ANY, "H RST")
        self.slider_ch2_horz = wx.Slider(self.panel_ch_2, wx.ID_ANY, 0, 0, 10)
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(10001, "Open", "")
        self.Bind(wx.EVT_MENU, self.open_menu_evt, id=10001)
        wxglade_tmp_menu.Append(10002, "Save", "")
        self.Bind(wx.EVT_MENU, self.save_menu_evt, id=10002)
        wxglade_tmp_menu.AppendSeparator()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Close", "")
        self.Bind(wx.EVT_MENU, self.close_menu_evt, id=item.GetId())
        self.frame_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(20001, "Manual", "")
        self.Bind(wx.EVT_MENU, self.manual_menu_evt, id=20001)
        wxglade_tmp_menu.Append(20002, "About", "")
        self.Bind(wx.EVT_MENU, self.about_menu_evt, id=20002)
        self.frame_menubar.Append(wxglade_tmp_menu, "Help")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.bitmap_button_record_evt, self.bitmap_button_record)
        self.Bind(wx.EVT_BUTTON, self.bitmap_button_play_evt, self.bitmap_button_play)
        self.Bind(wx.EVT_BUTTON, self.bitmap_button_pause_evt, self.bitmap_button_pause)
        self.Bind(wx.EVT_BUTTON, self.bitmap_button_stop_evt, self.bitmap_button_stop)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.button_time_evt, self.button_time)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.slider_time_evt, self.slider_time)
        self.Bind(wx.EVT_SPINCTRLDOUBLE, self.spin_ctrl_double_time_evt, self.spin_ctrl_double_time)
        self.Bind(wx.EVT_SPINCTRLDOUBLE, self.spin_ctrl_double_ch1_vd_evt, self.spin_ctrl_double_ch1_vd)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.slider_ch1_vd_evt, self.slider_ch1_vd)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.button_ch1_evt, self.button_ch1)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.slider_ch1_vert_evt, self.slider_ch1_vert)
        self.Bind(wx.EVT_BUTTON, self.button_ch1_v_rst_evt, self.button_ch1_v_rst)
        self.Bind(wx.EVT_BUTTON, self.button_ch1_h_rst_evt, self.button_ch1_h_rst)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.slider_ch1_horz_evt, self.slider_ch1_horz)
        self.Bind(wx.EVT_SPINCTRLDOUBLE, self.spin_ctrl_double_ch2_vd_evt, self.spin_ctrl_double_ch2_vd)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.slider_ch2_vd_evt, self.slider_ch2_vd)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.button_ch2_evt, self.button_ch2)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.slider_ch2_vert_evt, self.slider_ch2_vert)
        self.Bind(wx.EVT_BUTTON, self.button_ch2_v_rst_evt, self.button_ch2_v_rst)
        self.Bind(wx.EVT_BUTTON, self.button_ch2_h_rst_evt, self.button_ch2_h_rst)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.slider_ch2_horz_evt, self.slider_ch2_horz)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: BOXFrame.__set_properties
        self.SetTitle("BiosignalsOX")
        self.panel_canvas.SetMinSize((800, 600))
        self.panel_canvas.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.bitmap_button_record.SetSize(self.bitmap_button_record.GetBestSize())
        self.bitmap_button_play.SetSize(self.bitmap_button_play.GetBestSize())
        self.bitmap_button_pause.SetSize(self.bitmap_button_pause.GetBestSize())
        self.bitmap_button_stop.SetSize(self.bitmap_button_stop.GetBestSize())
        self.panel_ctrl.SetMinSize((300, 60))
        self.panel_time.SetMinSize((-1, 135))
        self.panel_time.SetBackgroundColour(wx.Colour(149, 149, 149))
        self.button_ch1.SetForegroundColour(wx.Colour(0, 0, 0))
        self.button_ch1_v_rst.SetMinSize((50, 29))
        self.button_ch1_h_rst.SetMinSize((50, 29))
        self.panel_ch_1.SetMinSize((-1, 135))
        self.panel_ch_1.SetBackgroundColour(wx.Colour(255, 180, 180))
        self.button_ch2.SetForegroundColour(wx.Colour(0, 0, 0))
        self.button_ch2_v_rst.SetMinSize((50, 29))
        self.button_ch2_h_rst.SetMinSize((50, 29))
        self.panel_ch_2.SetMinSize((-1, 135))
        self.panel_ch_2.SetBackgroundColour(wx.Colour(185, 234, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: BOXFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(4, 1, 13, 0)
        grid_sizer_11 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_14 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_15 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_16 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_12 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_13 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_5 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_9 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_8 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_10 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_6 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_7 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_3 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_4 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_17 = wx.FlexGridSizer(1, 4, 0, 0)
        grid_sizer_1.Add(self.panel_canvas, 1, wx.ALL, 20)
        grid_sizer_17.Add(self.bitmap_button_record, 0, wx.ALL, 0)
        grid_sizer_17.Add(self.bitmap_button_play, 0, 0, 0)
        grid_sizer_17.Add(self.bitmap_button_pause, 0, 0, 0)
        grid_sizer_17.Add(self.bitmap_button_stop, 0, 0, 0)
        self.panel_ctrl.SetSizer(grid_sizer_17)
        grid_sizer_2.Add(self.panel_ctrl, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.button_time, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        grid_sizer_3.Add(self.slider_time, 0, wx.ALL | wx.EXPAND, 5)
        grid_sizer_4.Add(self.spin_ctrl_double_time, 0, 0, 0)
        label_time = wx.StaticText(self.panel_time, wx.ID_ANY, "sec/div")
        label_time.SetForegroundColour(wx.Colour(0, 0, 0))
        grid_sizer_4.Add(label_time, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        grid_sizer_3.Add(grid_sizer_4, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.panel_time.SetSizer(grid_sizer_3)
        grid_sizer_3.AddGrowableRow(0)
        grid_sizer_3.AddGrowableRow(2)
        grid_sizer_3.AddGrowableCol(0)
        grid_sizer_2.Add(self.panel_time, 1, wx.EXPAND, 0)
        grid_sizer_7.Add(self.spin_ctrl_double_ch1_vd, 0, wx.ALL, 5)
        label_ch1 = wx.StaticText(self.panel_ch_1, wx.ID_ANY, "V/div")
        label_ch1.SetForegroundColour(wx.Colour(0, 0, 0))
        grid_sizer_7.Add(label_ch1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        grid_sizer_7.AddGrowableRow(0)
        grid_sizer_6.Add(grid_sizer_7, 1, wx.EXPAND, 0)
        grid_sizer_6.Add(self.slider_ch1_vd, 0, wx.ALL | wx.EXPAND, 10)
        grid_sizer_6.AddGrowableRow(1)
        grid_sizer_6.AddGrowableCol(0)
        grid_sizer_5.Add(grid_sizer_6, 1, wx.EXPAND, 0)
        grid_sizer_5.Add(self.button_ch1, 0, wx.ALIGN_CENTER | wx.ALL, 11)
        grid_sizer_9.Add(self.slider_ch1_vert, 0, wx.ALL | wx.EXPAND, 10)
        grid_sizer_10.Add(self.button_ch1_v_rst, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        grid_sizer_10.Add(self.button_ch1_h_rst, 0, wx.ALIGN_CENTER | wx.BOTTOM | wx.RIGHT | wx.TOP, 5)
        grid_sizer_10.AddGrowableCol(1)
        grid_sizer_8.Add(grid_sizer_10, 1, wx.EXPAND, 0)
        grid_sizer_8.Add(self.slider_ch1_horz, 0, wx.ALIGN_CENTER | wx.EXPAND | wx.RIGHT, 5)
        grid_sizer_9.Add(grid_sizer_8, 1, wx.EXPAND, 0)
        grid_sizer_9.AddGrowableRow(0)
        grid_sizer_9.AddGrowableCol(1)
        grid_sizer_5.Add(grid_sizer_9, 1, wx.EXPAND, 0)
        self.panel_ch_1.SetSizer(grid_sizer_5)
        grid_sizer_5.AddGrowableRow(0)
        grid_sizer_5.AddGrowableCol(0)
        grid_sizer_5.AddGrowableCol(2)
        grid_sizer_2.Add(self.panel_ch_1, 1, wx.EXPAND, 0)
        grid_sizer_13.Add(self.spin_ctrl_double_ch2_vd, 0, wx.ALL, 5)
        label_ch1_copy = wx.StaticText(self.panel_ch_2, wx.ID_ANY, "V/div")
        label_ch1_copy.SetForegroundColour(wx.Colour(0, 0, 0))
        grid_sizer_13.Add(label_ch1_copy, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
        grid_sizer_13.AddGrowableRow(0)
        grid_sizer_12.Add(grid_sizer_13, 1, wx.EXPAND, 0)
        grid_sizer_12.Add(self.slider_ch2_vd, 0, wx.ALL | wx.EXPAND, 10)
        grid_sizer_12.AddGrowableRow(1)
        grid_sizer_12.AddGrowableCol(0)
        grid_sizer_11.Add(grid_sizer_12, 1, wx.EXPAND, 0)
        grid_sizer_11.Add(self.button_ch2, 0, wx.ALIGN_CENTER | wx.ALL, 11)
        grid_sizer_14.Add(self.slider_ch2_vert, 0, wx.ALL | wx.EXPAND, 10)
        grid_sizer_16.Add(self.button_ch2_v_rst, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        grid_sizer_16.Add(self.button_ch2_h_rst, 0, wx.ALIGN_CENTER | wx.BOTTOM | wx.RIGHT | wx.TOP, 5)
        grid_sizer_16.AddGrowableCol(1)
        grid_sizer_15.Add(grid_sizer_16, 1, wx.EXPAND, 0)
        grid_sizer_15.Add(self.slider_ch2_horz, 0, wx.ALIGN_CENTER | wx.EXPAND | wx.RIGHT, 5)
        grid_sizer_14.Add(grid_sizer_15, 1, wx.EXPAND, 0)
        grid_sizer_14.AddGrowableRow(0)
        grid_sizer_14.AddGrowableCol(1)
        grid_sizer_11.Add(grid_sizer_14, 1, wx.EXPAND, 0)
        self.panel_ch_2.SetSizer(grid_sizer_11)
        grid_sizer_11.AddGrowableRow(0)
        grid_sizer_11.AddGrowableCol(0)
        grid_sizer_11.AddGrowableCol(2)
        grid_sizer_2.Add(self.panel_ch_2, 1, wx.EXPAND, 0)
        grid_sizer_2.AddGrowableRow(1)
        grid_sizer_2.AddGrowableRow(2)
        grid_sizer_2.AddGrowableRow(3)
        grid_sizer_2.AddGrowableCol(0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.BOTTOM | wx.RIGHT | wx.TOP, 20)
        grid_sizer_1.AddGrowableRow(0)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def bitmap_button_record_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'bitmap_button_record_evt' not implemented!")
        event.Skip()

    def bitmap_button_play_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'bitmap_button_play_evt' not implemented!")
        event.Skip()

    def bitmap_button_pause_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'bitmap_button_pause_evt' not implemented!")
        event.Skip()

    def bitmap_button_stop_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'bitmap_button_stop_evt' not implemented!")
        event.Skip()

    def button_time_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'button_time_evt' not implemented!")
        event.Skip()

    def slider_time_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'slider_time_evt' not implemented!")
        event.Skip()

    def spin_ctrl_double_time_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'spin_ctrl_double_time_evt' not implemented!")
        event.Skip()

    def spin_ctrl_double_ch1_vd_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'spin_ctrl_double_ch1_vd_evt' not implemented!")
        event.Skip()

    def slider_ch1_vd_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'slider_ch1_vd_evt' not implemented!")
        event.Skip()

    def button_ch1_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'button_ch1_evt' not implemented!")
        event.Skip()

    def slider_ch1_vert_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'slider_ch1_vert_evt' not implemented!")
        event.Skip()

    def button_ch1_v_rst_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'button_ch1_v_rst_evt' not implemented!")
        event.Skip()

    def button_ch1_h_rst_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'button_ch1_h_rst_evt' not implemented!")
        event.Skip()

    def slider_ch1_horz_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'slider_ch1_horz_evt' not implemented!")
        event.Skip()

    def spin_ctrl_double_ch2_vd_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'spin_ctrl_double_ch2_vd_evt' not implemented!")
        event.Skip()

    def slider_ch2_vd_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'slider_ch2_vd_evt' not implemented!")
        event.Skip()

    def button_ch2_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'button_ch2_evt' not implemented!")
        event.Skip()

    def slider_ch2_vert_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'slider_ch2_vert_evt' not implemented!")
        event.Skip()

    def button_ch2_v_rst_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'button_ch2_v_rst_evt' not implemented!")
        event.Skip()

    def button_ch2_h_rst_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'button_ch2_h_rst_evt' not implemented!")
        event.Skip()

    def slider_ch2_horz_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'slider_ch2_horz_evt' not implemented!")
        event.Skip()

    def open_menu_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'open_menu_evt' not implemented!")
        event.Skip()

    def save_menu_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'save_menu_evt' not implemented!")
        event.Skip()

    def close_menu_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'close_menu_evt' not implemented!")
        event.Skip()

    def manual_menu_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'manual_menu_evt' not implemented!")
        event.Skip()

    def about_menu_evt(self, event):  # wxGlade: BOXFrame.<event_handler>
        print("Event handler 'about_menu_evt' not implemented!")
        event.Skip()

# end of class BOXFrame

class MyApp(wx.App):
    def OnInit(self):
        self.BOXFrame = BOXFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.BOXFrame)
        self.BOXFrame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
